### ISSUE TITLE
`overprovision` Priority Class not applied?

### ISSUE THREAD

**Issue by pat-s** [codecentric/cluster-overprovisioner#13]
- EKS 1.23.7

In the `cluster-overprovisioner-cluster-overprovisioner-op-*` pods I don't see the `overprovision` class getting applied.

Changing `op.priorityClasses.default` (when enabled) results in a change for all pods in the cluster.

EDIT: just saw this is already addressed in #11. Any change this is getting merged still? I see it might be stale meanwhile?

**Comment by pat-s** [comment]
Sharing the current workaround:

`kubectl edit deployment.apps/cluster-overprovisioner-cluster-overprovisioner-op -n <namespace>`

In l.65 add 

```yml
priorityClassName: overprovision
```

NB: this must be done every time the deployment got updated externally, e.g. by the helm chart.

@grieshaber Would be really awesome to get this small fix in for a stable usage of this chart :)

**Comment by scott-kausler** [comment]
Note the above workaround can be simplified to:

`kubectl patch deployment cluster-overprovisioner-cluster-overprovisioner-op -p '{"spec": {"template": {"spec": {"priorityClassName": "overprovision"}}}}' -n <namespace>`

**Comment by achetronic** [comment]
Hello there. If this is fine, may be some reviews would be awesome! :) 

https://github.com/codecentric/cluster-overprovisioner/pull/15

**Comment by grieshaber** [comment]
Hey - sorry for the super late response. We lost a little track of this repo und did not find the time to maintain. I'll check this issue and your PR!

**Comment by achetronic** [comment]
> Hey - sorry for the super late response. We lost a little track of this repo und did not find the time to maintain. I'll check this issue and your PR!

Oh, don't worry about it. I will keep an eye on the repo and see if something else is needed. Please ping me when the PR is merged and thank you in advance!

**Comment by grieshaber** [comment]
Version 0.6.0 containing the neccessary fixes is now released. Thanks for the contribution!

**Comment by achetronic** [comment]
> Version 0.6.0 containing the neccessary fixes is now released. Thanks for the contribution!

NP! thank you for the project
